name: draggable_calendar_example
description: Example app for the draggable_calendar package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  draggable_calendar:
    path: ../  # This points to the root package
  flutter_bloc: ^9.1.0
  equatable: ^2.0.0
  uuid: ^4.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true