name: draggable_calendar
description: A Flutter package for a draggable calendar with event management capabilities
version: 0.1.0
homepage: https://github.com/yourusername/draggable_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  syncfusion_flutter_calendar: ">=20.0.0 <30.0.0"
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: